version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
    groups:
      all:
        patterns: ["*"]

  - package-ecosystem: devcontainers
    directory: /
    schedule:
      interval: "monthly"
    groups:
      all:
        patterns: ["*"]

  - package-ecosystem: docker
    directory: /.devcontainer
    schedule:
      interval: monthly
    groups:
      all:
        patterns: ["*"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      all:
        patterns: ["*"]
