default_install_hook_types:
  - pre-commit
  - post-checkout
  - post-merge

fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-illegal-windows-names
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
        args: ["--unsafe"]
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: name-tests-test
        args: ["--pytest-test-first"]
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.6.6
    hooks:
      - id: uv-lock
  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: uv run ruff check --fix
        language: system
        types: [python]
        pass_filenames: false
      - id: format
        name: format
        entry: uv run ruff format
        language: system
        types: [python]
        pass_filenames: false
      - id: versioncheck
        name: versioncheck
        entry: uv run vermin .
        language: system
        types: [python]
        pass_filenames: false
      - id: licensecheck
        name: licensecheck
        entry: uv run licensecheck
        language: system
        files: ^pyproject\.toml|uv\.lock$
        pass_filenames: false
      - id: typecheck
        name: typecheck
        entry: uv run pyright --warnings
        language: system
        types: [python]
        pass_filenames: false
      - id: test
        name: test
        entry: uv run pytest
        language: system
        types: [python]
        pass_filenames: false
