coverage:
  status:
    project:
      default:
        informational: true
        target: auto
    patch:
      default:
        informational: true

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
