coverage:
  status:
    project:
      default:
        informational: true
        target: auto
    patch:
      default:
        informational: true
    changes:
      default:
        informational: true
        branches:
          - source
          - target

codecov:
  require_ci_to_pass: false
  notify:
    wait_for_ci: false

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  hide_project_coverage: false
  require_base: false
  require_head: true
