name: check

on:
  - push
  - pull_request

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: "3.10"

      - name: Set up poetry
        uses: abatilo/actions-poetry@3765cf608f2d4a72178a9fc5b918668e542b89b1 # v4.0.0
        with:
          poetry-version: "2.0.0"

      - name: Install dependencies
        run: poetry install --only main,dev

      - name: Run linter
        run: poetry run poe lint

      - name: Run formatter
        run: poetry run poe format

      - name: Run version check
        run: poetry run poe versioncheck

      - name: Install test dependencies
        run: poetry install --only main,dev,test

      - name: Run tests
        run: poetry run poe test

      - name: Install types
        run: poetry install --only main,dev,test,types

      - name: Run type checking
        run: poetry run poe typecheck
