name: check

on:
  - push
  - pull_request

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Cache Nix store
        uses: DeterminateSystems/magic-nix-cache-action@v9

      - name: Install dependencies
        run: nix develop --command uv sync --all-groups

      - name: Run linter
        run: nix develop --command just lint

      - name: Run formatter
        run: nix develop --command just format

      - name: Run tests
        run: nix develop --command just test --cov-branch --cov-report=xml --junitxml=junit.xml

      - name: Run type checking
        run: nix develop --command just typecheck

      - name: Upload coverage results to Codecov
        uses: codecov/codecov-action@v5.5.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1.2.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
